### ISSUE TITLE
Project switcher drop-down not working

### ISSUE THREAD

**Issue by enbarca** [xapix-io/beta#6]
Top of left dashboard. Unable to switch between projects.

**Comment by oliver-xapix-io** [comment]
I'll take a look tomorrow. Sorry, just got the email notification about this... :/

**Comment by pickledolives** [comment]
Works for me? Please provide more info on what screen, browser, etc.

**Comment by pickledolives** [comment]
mouseovering dropdown hides it. Looks like the menu below overlaps it. Problem appears on Chrome

**Comment by oliver-xapix-io** [comment]
attempt to fix this by stricter twitter-bootstrap'ish element isolation with https://github.com/pickledolives/streapi/commit/b42c89c923dc7c216010b79058fb227d8a7af979

**Comment by oliver-xapix-io** [comment]
turned out to have fixed the issue -> close
